### ISSUE TITLE
Neptune Logger problem

### ISSUE THREAD

**Issue by LJ-00** [fcakyon/yolov5-pip#68]
Hello, 

Thanks for all of this great work. 

I am able to train, but when I try to include the api token and project id for neptune, I get the following result. 

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\yolov5\utils\loggers\__init__.py", line 98, in __init__
    self.neptune = NeptuneLogger(self.opt)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\yolov5\utils\loggers\neptune\neptune_utils.py", line 29, in __init__
    self.track_dataset(opt)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\yolov5\utils\loggers\neptune\neptune_utils.py", line 51, in track_dataset
    self.neptune_run["data"].track_files(yolo_s3_data_dir)

UnboundLocalError: local variable 'yolo_s3_data_dir' referenced before assignment

**Comment by fcakyon** [comment]
@LJ-00  thanks a lot for noticing this bug (it happens when you dont provide `--s3_upload_dir`)!

It should be fixed with https://github.com/fcakyon/yolov5-pip/pull/69.

Can you please update your yolov5-pip installation with?

`pip install git+https://github.com/fcakyon/yolov5-pip.git@fix-neptune`

If it is fixed please repond here so that I will release `v6.0.6` with this neptune logging fix!

**Comment by LJ-00** [comment]
- Unfortunately, that alone doesn't solve the problem. 

- In a different run, after doing that pip install, I added a directory 
--s3_upload_dir' mydirectory
but I still get the same error.  

- On a third iteration, I added that default='./upload' to the yaml file and it can runs for one epch, but then I get an error when Iit tries to save to upload weights to aws (which i don't have).  Is there a way to disable this upload? I tried setting upload dataset to 'store_false' but that got me the original error of this post. 

  File "D:\yolov5\trainv.py", line 725, in <module>
    main(opt)

  File "D:\yolov5\trainv.py", line 622, in main
    train(opt.hyp, opt, device, callbacks)

  File "D:\yolov5\trainv.py", line 466, in train
    result = upload_file_to_s3(local_file=str(best), s3_file=s3_file)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\yolov5\utils\aws.py", line 37, in upload_file_to_s3
    s3.upload_file(local_file, bucket, s3_key)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\boto3\s3\inject.py", line 130, in upload_file
    return transfer.upload_file(

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\boto3\s3\transfer.py", line 287, in upload_file
    future.result()

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\s3transfer\futures.py", line 106, in result
    return self._coordinator.result()

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\s3transfer\futures.py", line 265, in result
    raise self._exception

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\s3transfer\tasks.py", line 126, in __call__
    return self._execute_main(kwargs)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\s3transfer\tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\s3transfer\tasks.py", line 332, in _main
    response = client.create_multipart_upload(

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\botocore\client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\botocore\client.py", line 691, in _make_api_call
    request_dict = self._convert_to_request_dict(

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\botocore\client.py", line 737, in _convert_to_request_dict
    api_params = self._emit_api_params(

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\botocore\client.py", line 766, in _emit_api_params
    self.meta.events.emit(

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)

  File "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\botocore\handlers.py", line 243, in validate_bucket_name
    raise ParamValidationError(report=error_msg)

ParamValidationError: Parameter validation failed:
Invalid bucket name "D:": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"

**Comment by fcakyon** [comment]
@LJ-00 just to confirm:
- You dont have `yolo_s3_data_dir:` field in your data.yaml.
- You dont set `--s3_upload_dir` argument during training.
- You dont set `--upload_dataset` argument during training.

Right?

**Comment by fcakyon** [comment]
@LJ-00 I have pushed another changes to `@fix-neptune` branch.

Can you `pip uninstall yolov5` then `pip install git+https://github.com/fcakyon/yolov5-pip.git@fix-neptune` and try to train again?

**Comment by fcakyon** [comment]
> Is there a way to disable this upload?

Yes when you **dont** add `--upload_dataset` and `--s3_upload_dir` arguments, dataset and weight upload is disabled.

**Comment by LJ-00** [comment]
information in my yaml data file: 
train: D:\datasets\data\images  ]
val: D:\datasets\data\images  
test: D:\datasets\data\validation 
yolo_s3_data_dir: D:\yolov5\upload
# Classes
nc: 1  # number of classes
names: ['data']  # class names

yolov5 train --data data.yaml --cfg yolov5x.yaml --batch-size 4 --img 640 --neptune_project team/test --neptune_token tokennumber

It is running and uploading the data to neptune! 

Thanks! 

It does give me the following message: 

 [00:00<?, ?it/s]Error occurred during asynchronous operation processing:

----NeptuneUnhandledArtifactProtocolException------------------------------------

You have used a Neptune Artifact to track a file with scheme unhandled by this client (d).

But it is uploading the data. 

Thanks! I didn't want to use another logger. Hopefully it continues to work after more epochs.

**Comment by fcakyon** [comment]
@LJ-00 you have to remove this line from yaml: 

<s> yolo_s3_data_dir: D:\yolov5\upload </s>

to disable upload.

**Comment by LJ-00** [comment]
I deleted that line, and I still get 

----NeptuneUnhandledArtifactProtocolException------------------------------------

You have used a Neptune Artifact to track a file with scheme unhandled by this client (d).

**Comment by fcakyon** [comment]
@LJ-00 have you tried deleting local (faulty) neptune folders files? I cannot recreate this issue. When I start traning with neptune info without aws info, it does not give me errors.
