### ISSUE TITLE
Google Colab error

### ISSUE THREAD

**Issue by orphan2020** [fcakyon/yolov5-pip#7]
when trying to use the pip wrapper in colab I get the following error:

# init yolov5 model
yolov5 = YOLOv5(model_path,device)

=>

Downloading https://github.com/ultralytics/yolov5/releases/download/v4.0/yolov5s.pt to yolov5/weights/yolov5s.pt...
Download error: [Errno 2] No such file or directory: 'yolov5/weights/tmpr8j0fg5z'
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/yolov5/utils/google_utils.py in attempt_download(file, repo)
     69                 print(f'Downloading {url} to {file}...')
---> 70                 torch.hub.download_url_to_file(url, file)
     71                 assert file.exists() and file.stat().st_size > 1E6  # check

7 frames
/usr/local/lib/python3.7/dist-packages/torch/hub.py in download_url_to_file(url, dst, hash_prefix, progress)
    407     dst_dir = os.path.dirname(dst)
--> 408     f = tempfile.NamedTemporaryFile(delete=False, dir=dst_dir)
    409 

/usr/lib/python3.7/tempfile.py in NamedTemporaryFile(mode, buffering, encoding, newline, suffix, prefix, dir, delete)
    685 
--> 686     (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
    687     try:

/usr/lib/python3.7/tempfile.py in _mkstemp_inner(dir, pre, suf, flags, output_type)
    396         try:
--> 397             fd = _os.open(file, flags, 0o600)
    398         except FileExistsError:

FileNotFoundError: [Errno 2] No such file or directory: 'yolov5/weights/tmpr8j0fg5z'

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/yolov5/utils/google_utils.py in attempt_download(file, repo)
     73                 print(f'Download error: {e}')
---> 74                 assert redundant, 'No secondary mirror'
     75                 url = f'https://storage.googleapis.com/{repo}/ckpt/{name}'

AssertionError: No secondary mirror

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-9-8c469e14af09> in <module>()
      1 # init yolov5 model
----> 2 yolov5 = YOLOv5(model_path, device)

/usr/local/lib/python3.7/dist-packages/yolov5/helpers.py in __init__(self, model_path, device, load_on_init)
    104         self.device = device
    105         if load_on_init:
--> 106             self.model = load_model(model_path=model_path, device=device, autoshape=True)
    107         else:
    108             self.model = None

/usr/local/lib/python3.7/dist-packages/yolov5/helpers.py in load_model(model_path, device, autoshape)
     48     sys.path.insert(0, yolov5_folder_dir)
     49 
---> 50     attempt_download(model_path)  # download if not found locally
     51     model = torch.load(model_path, map_location=torch.device(device))
     52     if isinstance(model, dict):

/usr/local/lib/python3.7/dist-packages/yolov5/utils/google_utils.py in attempt_download(file, repo)
     78             finally:
     79                 if not file.exists() or file.stat().st_size < 1E6:  # check
---> 80                     file.unlink(missing_ok=True)  # remove partial downloads
     81                     print(f'ERROR: Download failure: {msg}')
     82                 print('')

TypeError: unlink() got an unexpected keyword argument 'missing_ok'
SEARCH STACK OVERFLOW

**Comment by fcakyon** [comment]
thanks for reporting. should be fixed with [v4.0.7](https://pypi.org/project/yolov5/4.0.7/#history). try `pip install -U yolov5`

**Comment by orphan2020** [comment]
Unfortunately still throwing error: 

Downloading https://github.com/ultralytics/yolov5/releases/download/v4.0/yolov5s.pt to yolov5/weights/yolov5s.pt...
Download error: [Errno 2] No such file or directory: 'yolov5/weights/tmpfqol0itk'
ERROR: Download failure: yolov5/weights/yolov5s.pt missing, try downloading from https://github.com/ultralytics/yolov5/releases/

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-15-8c469e14af09> in <module>()
      1 # init yolov5 model
----> 2 yolov5 = YOLOv5(model_path, device)

4 frames
/usr/local/lib/python3.7/dist-

**Comment by fcakyon** [comment]
@orphan2020 Can you please tell me what you in detail? If you could provide minimal code sample to recreate the issue that would be great.

At the moment I cannot recreate the issue, it works fine for me.

**Comment by orphan2020** [comment]
In Google Colab: 

1. Cell: 
pip install -U yolov5  # run OK !

2. Cell: 
from PIL import Image
from yolov5 import YOLOv5 # run OK !

3. Cell: 
set model params
model_path = "yolov5/weights/yolov5s.pt" # it automatically downloads yolov5s model to given path
device = "cuda" # or "cpu"  # run OK

4. Cell: 
# init yolov5 model
yolov5 = YOLOv5(model_path, device)

run = > ERROR:

Downloading https://github.com/ultralytics/yolov5/releases/download/v4.0/yolov5s.pt to yolov5/weights/yolov5s.pt...
Download error: [Errno 2] No such file or directory: 'yolov5/weights/tmpz7dccws_'
ERROR: Download failure: yolov5/weights/yolov5s.pt missing, try downloading from https://github.com/ultralytics/yolov5/releases/

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

<ipython-input-4-8c469e14af09> in <module>()
      1 # init yolov5 model
----> 2 yolov5 = YOLOv5(model_path, device)

4 frames

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in __init__(self, name, mode)
    209 class _open_file(_opener):
    210     def __init__(self, name, mode):
--> 211         super(_open_file, self).__init__(open(name, mode))
    212 
    213     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'yolov5/weights/yolov5s.pt'

------------------------------------------------------------------------------------------------------------------------
Interestingly, the data browser on the left in google colab doesnt even show that anyting was downloaded, not even a yolov5 folder as you can see in the screnshot:

[![Screenshot-2021-03-24-Google-Colaboratory.png](https://i.postimg.cc/NG9Zsp5M/Screenshot-2021-03-24-Google-Colaboratory.png)](https://postimg.cc/9z2L1PP5)

**Comment by fcakyon** [comment]
You have to create yolov5/weights/ folder beforehand. In your ss there isnt any yolov5/weight/ folder.

**Comment by fcakyon** [comment]
Added automatic folder directory creation at 4.0.9. `pip install -U yolov5` to fix the issue.
